services:

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=last_db
      - POSTGRES_USER=last
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U last -d last_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "
      python manage.py migrate --no-input &&
      python manage.py collectstatic --no-input &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=last_db
      - POSTGRES_USER=last
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: